import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {api,syncParticipant} from '../server/gate.mjs';
const sqlite=new DatabaseSync(':memory:');
sqlite.exec(readFileSync(new URL('../drizzle/0000_friendly_ben_grimm.sql',import.meta.url),'utf8'));
const prepare=sql=>({bind(...args){return {first:async()=>sqlite.prepare(sql).get(...args)||null,run:async()=>sqlite.prepare(sql).run(...args),_sql:sql,_args:args};}});
const DB={prepare,batch:async items=>{sqlite.exec('BEGIN');try{const out=items.map(x=>sqlite.prepare(x._sql).run(...x._args));sqlite.exec('COMMIT');return out;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const ledger=new Map();let offline=false;
globalThis.fetch=async(url,opts)=>{if(offline)throw new Error('simulated offline');const p=JSON.parse(opts.body);assert.equal(p.secret,'test-secret');const old=ledger.get(p.operationId);if(!old||old.version<=p.version)ledger.set(p.operationId,p);return Response.json({ok:true,version:ledger.get(p.operationId).version,participantNumber:p.participantNumber});};
const env={DB,LEDGER_SECRET:'test-secret',LEDGER_URL:'https://example.invalid/mock-ledger'};
const portal='https://suiyoukai-portal.c84s4n967v.chatgpt.site';
const flower='https://jfsxxxib-wq.github.io';
let ip=0;
async function call(path,{body,cookie,origin=portal,token}={}){const headers={'Origin':origin,'CF-Connecting-IP':String(++ip)};if(cookie)headers.Cookie=cookie;if(token)headers.Authorization='Bearer '+token;const r=await api(new Request(portal+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('Set-Cookie')?.split(';')[0]};}
const names={familyName:'接続',givenName:'確認',requestKey:'a'.repeat(64)};
let r=await call('/api/registration',{body:names});assert.equal(r.status,200);assert.equal(r.data.participant.synced,true);const cookie=r.cookie;const number=r.data.participant.participantNumber;assert.match(number,/^\d{8}$/);assert.equal(ledger.size,1);
r=await call('/api/registration',{body:names});assert.equal(r.data.participant.participantNumber,number);assert.equal(ledger.size,1);assert.equal(r.cookie,cookie);
r=await call('/api/registration',{cookie});assert.equal(r.data.participant.participantNumber,number);
r=await call('/api/registration',{cookie,body:{...names,givenName:'確認修正'}});assert.equal(r.data.participant.participantNumber,number);assert.equal(ledger.size,1);assert.equal([...ledger.values()][0].givenName,'確認修正');
r=await call('/api/registration',{body:{...names,requestKey:'b'.repeat(64)}});assert.notEqual(r.data.participant.participantNumber,number);assert.equal(ledger.size,2);
r=await call('/api/registration',{body:names,origin:'https://other.invalid'});assert.equal(r.status,403);
offline=true;r=await call('/api/registration',{body:{...names,requestKey:'c'.repeat(64)}});assert.equal(r.status,503);assert.equal(r.data.participant.synced,false);const delayedCookie=r.cookie;
offline=false;r=await call('/api/registration',{cookie:delayedCookie});assert.equal(r.data.participant.synced,true);assert.equal(ledger.size,3);
r=await call('/api/handoff',{body:{}});assert.equal(r.status,401);
r=await call('/api/handoff',{cookie,body:{}});assert.equal(r.status,200);const ticket=new URL(r.data.url).hash.split('=')[1];
const redeem={ticket,appNumber:'12345678',deviceKey:'d'.repeat(64)};
offline=true;r=await call('/api/flower/redeem',{body:redeem,origin:flower});assert.equal(r.status,200);assert.equal(r.data.participant.synced,false);const token=r.data.token;
offline=false;r=await call('/api/flower/redeem',{body:redeem,origin:flower});assert.equal(r.data.token,token);assert.equal(r.data.participant.synced,true);assert.equal(ledger.size,3);assert.equal([...ledger.values()][0].appNumber,'12345678');
r=await call('/api/flower/redeem',{body:{...redeem,deviceKey:'e'.repeat(64)},origin:flower});assert.equal(r.status,409);
r=await call('/api/flower/session',{origin:flower,token});assert.equal(r.data.participant.participantNumber,number);
r=await call('/api/flower/session',{origin:flower,token:'f'.repeat(64)});assert.equal(r.status,401);
r=await call('/api/flower/session',{origin:'https://other.invalid',token});assert.equal(r.status,403);
r=await call('/api/handoff',{cookie,body:{}});const expired=new URL(r.data.url).hash.split('=')[1];sqlite.exec('UPDATE gate_tickets SET expires=0');
r=await call('/api/flower/redeem',{body:{...redeem,ticket:expired},origin:flower});assert.equal(r.status,409);
assert.equal(sqlite.prepare('SELECT count(*) AS n FROM gate_participants').get().n,3);
globalThis.fetch=async()=>Response.json({ok:true,service:'suiyoukai-official-registration',version:1});
assert.equal(await syncParticipant(env,{id:'not-saved',number:'90000000',version:1,synced:0}),false,'Service availability is not a write acknowledgement');
console.log('PASS: registration, stable IDs, retry after lost response, separate same-name identities, sheet outage recovery, same-origin protection, authenticated handoff, one-use tickets, device retry, expiry. Real sheet not used.');
